[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pyusb",
    "pyserial",
    "lxml",
    "docopt",
    "pycryptodome",
    "colorama",
    "Exscript",
    "requests",
    "passlib",
    "usb"
]
build-backend = "setuptools.build_meta"
